apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio-app
  labels:
    app: backend
spec:
  replicas: 1   # reduced to 1 to fit t2.micro node, can increase later if node type changes
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 402298071739.dkr.ecr.us-east-1.amazonaws.com/portfolio-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
