apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: portfolio-app
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
