apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: portfolio-app
  labels:
    app: frontend
spec:
  replicas: 1   # reduced to 1 to fit t2.micro node
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 402298071739.dkr.ecr.us-east-1.amazonaws.com/portfolio-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service.portfolio-app.svc.cluster.local:5000"
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 150m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
